# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QPushButton, QWidget
import cv2
from pyzbar import pyzbar
from main_interface import Ui_Main_interface

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(950, 650)
        MainWindow.setMinimumSize(QtCore.QSize(950, 650))
        MainWindow.setMaximumSize(QtCore.QSize(950, 650))

        self.camera = cv2.VideoCapture(0)

        self.Name = ''
        self.Dob = ''
        self.Addrees = ''

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -30, 475, 650))
        self.label.setMinimumSize(QtCore.QSize(475, 650))
        self.label.setMaximumSize(QtCore.QSize(475, 650))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("image/login_background.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(660, 150, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_2.setStyleSheet("color: #29BABF;")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(550, 220, 341, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setStyleSheet('''
            QPushButton {
                font-weight: bold;
                color: #29BABF;
                border: 2px solid #29BABF;
                border-radius: 20px;
            }
            QPushButton:hover {
                background-color: #29BABF;
                color: white;
            }
            QPushButton:pressed {
                background-color: #29BABF;
                border-style: inset;
            }
        ''')
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(550, 310, 341, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.setStyleSheet('''
            QPushButton {
                font-weight: bold;
                color: #29BABF;
                border: 2px solid #29BABF;
                border-radius: 20px;
            }
            QPushButton:hover {
                background-color: #29BABF;
                color: white;
            }
            QPushButton:pressed {
                background-color: #29BABF;
                border-style: inset;
            }        
        ''')
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(550, 400, 341, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.setStyleSheet('''
            QPushButton {
                font-weight: bold;
                color: #29BABF;
                border: 2px solid #29BABF;
                border-radius: 20px;
            }
            QPushButton:hover {
                background-color: #29BABF;
                color: white;
            }
            QPushButton:pressed {
                background-color: #29BABF;
                border-style: inset;
            }
        ''')
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 950, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        #Các button ở login_screen
        self.pushButton.clicked.connect(self.login_QR)
        self.pushButton.clicked.connect(self.main_interface)
        self.pushButton.clicked.connect(MainWindow.close)
        self.pushButton.clicked.connect(self.Moving_Data_QR)
        self.pushButton_3.clicked.connect(self.exit)

    def main_interface(self):
        self.mainInterface = QtWidgets.QMainWindow()
        self.ui = Ui_Main_interface()
        self.ui.setupUi(self.mainInterface)
        self.mainInterface.show()

    def exit(self):
        MainWindow.close()

    def login_QR(self):
        while True:
            ret, frame = self.camera.read()
            barcodes = pyzbar.decode(frame)
            truth = False
            for barcode in barcodes:
                (x, y, w, h) = barcode.rect
                cv2.rectangle(frame, (x, y), (x + w, y + h), (0, 255, 255), 2)
                barcodeData = barcode.data.decode('utf-8')
                self.Name = barcodeData[14:27].strip()
                self.Dob = barcodeData[30:36].strip()
                self.Addrees = barcodeData[41:-9].strip()
                print(f"Họ tên: {self.Name}")
                print(f"Ngày sinh: {self.Dob}")
                print(f"Địa chỉ: {self.Addrees}")
                truth = True
            cv2.imshow('Doc MA VACH - MA QR', frame)
            if cv2.waitKey(1) == ord('q') or truth == True:
                break
        self.camera.release()
        cv2.destroyAllWindows()

    def Moving_Data_QR(self):
        self.ui.label_2.setText(self.Name)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Đăng nhập"))
        self.pushButton.setText(_translate("MainWindow", "Đăng nhập bằng mã QR "))
        self.pushButton_2.setText(_translate("MainWindow", "Đăng nhập "))
        self.pushButton_3.setText(_translate("MainWindow", "Thoát "))
import source


if __name__ == "__main__":
    import sys
    name = ""
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())